# Form implementation generated from reading ui file '.\src\ui\design.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(332, 117)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.launch_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.launch_button.setMinimumSize(QtCore.QSize(0, 25))
        self.launch_button.setObjectName("launch_button")
        self.gridLayout.addWidget(self.launch_button, 5, 0, 1, 1)
        self.status_progress_bar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.status_progress_bar.setMinimumSize(QtCore.QSize(0, 25))
        self.status_progress_bar.setProperty("value", 24)
        self.status_progress_bar.setObjectName("status_progress_bar")
        self.gridLayout.addWidget(self.status_progress_bar, 1, 0, 1, 1)
        self.status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.status_label.setMinimumSize(QtCore.QSize(0, 25))
        self.status_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenRGB installer"))
        self.launch_button.setText(_translate("MainWindow", "Launch OpenRGB"))
        self.status_label.setText(_translate("MainWindow", "Installing"))
